### ISSUE TITLE
Demo carsh

### ISSUE THREAD

**Issue by Allen-cxl** [blessedCode07/trapezium-view#2] opened 2021-04-09 03:12 UTC
This project looks great, but the demo runs an error. Below is the error log.

Caused by: android.view.InflateException: Binary XML file line #22: com.arkapp.trapeziumview.TrapeziumCustomView cannot be cast to android.view.ViewGroup
     Caused by: java.lang.ClassCastException: com.arkapp.trapeziumview.TrapeziumCustomView cannot be cast to android.view.ViewGroup

**Comment by abdulrehmank7** [comment] 2021-04-09 15:47
@Allen-cxl the issue is fixed in the latest release.

**Closed as completed by abdulrehmank7** 2021-04-09 15:47 UTC

**Comment by Allen-cxl** [comment] 2021-04-14 10:09
> @Allen-cxl the issue is fixed in the latest release.

It's ok，thinks！Can you provide a trapezium-layout?  for RelativeLayout

**Comment by abdulrehmank7** [comment] 2021-04-14 17:35
@Allen-cxl sure in future updates.
